return {
    -- MainBackground
    [0] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- Titlebar
    [1] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- Dropdown
    [2] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- Tooltip
    [3] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- Notification
    [4] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- ScrollBar
    [5] = {
        [0] = Color3.fromRGB(56, 56, 56),
        [2] = Color3.fromRGB(70, 70, 70),
        [3] = Color3.fromRGB(34, 34, 34),
        [4] = Color3.fromRGB(70, 70, 70)
    },
    -- ScrollBarBackground
    [6] = {
        [0] = Color3.fromRGB(41, 41, 41)
    },
    -- TabBar
    [7] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- Tab
    [8] = {
        [0] = Color3.fromRGB(53, 53, 53),
        [1] = Color3.fromRGB(37, 37, 37),
        [4] = Color3.fromRGB(42, 42, 42)
    },
    -- FilterButtonDefault
    [9] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- FilterButtonHover
    [10] = {
        [0] = Color3.fromRGB(37, 37, 37)
    },
    -- FilterButtonChecked
    [11] = {
        [0] = Color3.fromRGB(28, 28, 28)
    },
    -- FilterButtonAccent
    [12] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- FilterButtonBorder
    [13] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- FilterButtonBorderAlt
    [14] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- RibbonTab
    [15] = {
        [0] = Color3.fromRGB(53, 53, 53),
        [1] = Color3.fromRGB(46, 46, 46),
        [4] = Color3.fromRGB(46, 46, 46)
    },
    -- RibbonTabTopBar
    [16] = {
        [0] = Color3.fromRGB(53, 181, 255)
    },
    -- Button
    [17] = {
        [0] = Color3.fromRGB(60, 60, 60),
        [1] = Color3.fromRGB(0, 162, 255),
        [2] = Color3.fromRGB(41, 41, 41),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- MainButton
    [18] = {
        [0] = Color3.fromRGB(0, 162, 255),
        [2] = Color3.fromRGB(0, 116, 189),
        [4] = Color3.fromRGB(50, 181, 255)
    },
    -- RibbonButton
    [19] = {
        [0] = Color3.fromRGB(46, 46, 46),
        [1] = Color3.fromRGB(28, 28, 28),
        [2] = Color3.fromRGB(28, 28, 28),
        [4] = Color3.fromRGB(37, 37, 37)
    },
    -- ViewPortBackground
    [20] = {
        [0] = Color3.fromRGB(37, 37, 37)
    },
    -- InputFieldBackground
    [21] = {
        [0] = Color3.fromRGB(37, 37, 37),
        [4] = Color3.fromRGB(66, 66, 66),
        [3] = Color3.fromRGB(53, 53, 53)
    },
    -- Item
    [22] = {
        [0] = Color3.fromRGB(46, 46, 46),
        [1] = Color3.fromRGB(11, 90, 175),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- TableItem
    [23] = {
        [0] = Color3.fromRGB(42, 42, 42),
        [1] = Color3.fromRGB(11, 90, 175),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- CategoryItem
    [24] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- GameSettingsTableItem
    [25] = {
        [0] = Color3.fromRGB(42, 42, 42),
        [1] = Color3.fromRGB(11, 90, 175),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- GameSettingsTooltip
    [26] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- EmulatorBar
    [27] = {
        [0] = Color3.fromRGB(46, 46, 46),
        [4] = Color3.fromRGB(37, 37, 37)
    },
    -- EmulatorDropDown
    [28] = {
        [0] = Color3.fromRGB(46, 46, 46),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- ColorPickerFrame
    [29] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- CurrentMarker
    [30] = {
        [0] = Color3.fromRGB(66, 66, 66),
        [1] = Color3.fromRGB(11, 90, 175)
    },
    -- Border
    [31] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- DropShadow
    [32] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- Shadow
    [33] = {
        [0] = Color3.fromRGB(64, 64, 64)
    },
    -- Light
    [34] = {
        [0] = Color3.fromRGB(64, 64, 64)
    },
    -- Dark
    [35] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- Mid
    [36] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- MainText
    [37] = {
        [0] = Color3.fromRGB(204, 204, 204),
        [1] = Color3.fromRGB(255, 255, 255),
        [3] = Color3.fromRGB(85, 85, 85),
        [4] = Color3.fromRGB(255, 255, 255)
    },
    -- SubText
    [38] = {
        [0] = Color3.fromRGB(170, 170, 170),
        [3] = Color3.fromRGB(85, 85, 85)
    },
    -- TitlebarText
    [39] = {
        [0] = Color3.fromRGB(170, 170, 170),
        [3] = Color3.fromRGB(85, 85, 85)
    },
    -- BrightText
    [40] = {
        [0] = Color3.fromRGB(229, 229, 229)
    },
    -- DimmedText
    [41] = {
        [0] = Color3.fromRGB(102, 102, 102),
        [1] = Color3.fromRGB(170, 170, 170)
    },
    -- LinkText
    [42] = {
        [0] = Color3.fromRGB(53, 181, 255)
    },
    -- WarningText
    [43] = {
        [0] = Color3.fromRGB(255, 142, 60)
    },
    -- ErrorText
    [44] = {
        [0] = Color3.fromRGB(255, 68, 68)
    },
    -- InfoText
    [45] = {
        [0] = Color3.fromRGB(128, 215, 255)
    },
    -- SensitiveText
    [46] = {
        [0] = Color3.fromRGB(209, 93, 255)
    },
    -- ScriptSideWidget
    [47] = {
        [0] = Color3.fromRGB(37, 37, 37)
    },
    -- ScriptBackground
    [48] = {
        [0] = Color3.fromRGB(37, 37, 37)
    },
    -- ScriptText
    [49] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- ScriptSelectionText
    [50] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- ScriptSelectionBackground
    [51] = {
        [0] = Color3.fromRGB(11, 90, 175)
    },
    -- ScriptFindSelectionBackground
    [52] = {
        [0] = Color3.fromRGB(141, 118, 0)
    },
    -- ScriptMatchingWordSelectionBackground
    [53] = {
        [0] = Color3.fromRGB(85, 85, 85)
    },
    -- ScriptOperator
    [54] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- ScriptNumber
    [55] = {
        [0] = Color3.fromRGB(255, 198, 0)
    },
    -- ScriptString
    [56] = {
        [0] = Color3.fromRGB(173, 241, 149)
    },
    -- ScriptComment
    [57] = {
        [0] = Color3.fromRGB(102, 102, 102)
    },
    -- ScriptKeyword
    [58] = {
        [0] = Color3.fromRGB(248, 109, 124)
    },
    -- ScriptBuiltInFunction
    [59] = {
        [0] = Color3.fromRGB(132, 214, 247)
    },
    -- ScriptWarning
    [60] = {
        [0] = Color3.fromRGB(255, 115, 21)
    },
    -- ScriptError
    [61] = {
        [0] = Color3.fromRGB(255, 0, 0)
    },
    -- ScriptInformation
    [62] = {
        [0] = Color3.fromRGB(79, 79, 79)
    },
    -- ScriptHint
    [63] = {
        [0] = Color3.fromRGB(0, 139, 219)
    },
    -- ScriptWhitespace
    [64] = {
        [0] = Color3.fromRGB(85, 85, 85)
    },
    -- ScriptRuler
    [65] = {
        [0] = Color3.fromRGB(102, 102, 102)
    },
    -- DocViewCodeBackground
    [66] = {
        [0] = Color3.fromRGB(66, 66, 66)
    },
    -- DebuggerCurrentLine
    [67] = {
        [0] = Color3.fromRGB(42, 60, 76)
    },
    -- DebuggerErrorLine
    [68] = {
        [0] = Color3.fromRGB(76, 42, 42)
    },
    -- DiffFilePathText
    [69] = {
        [0] = Color3.fromRGB(170, 170, 170)
    },
    -- DiffTextHunkInfo
    [70] = {
        [0] = Color3.fromRGB(170, 170, 170)
    },
    -- DiffTextNoChange
    [71] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- DiffTextAddition
    [72] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- DiffTextDeletion
    [73] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- DiffTextSeparatorBackground
    [74] = {
        [0] = Color3.fromRGB(49, 57, 73)
    },
    -- DiffTextNoChangeBackground
    [75] = {
        [0] = Color3.fromRGB(27, 31, 32)
    },
    -- DiffTextAdditionBackground
    [76] = {
        [0] = Color3.fromRGB(48, 63, 44)
    },
    -- DiffTextDeletionBackground
    [77] = {
        [0] = Color3.fromRGB(72, 30, 24)
    },
    -- DiffLineNum
    [78] = {
        [0] = Color3.fromRGB(170, 170, 170)
    },
    -- DiffLineNumSeparatorBackground
    [79] = {
        [0] = Color3.fromRGB(60, 83, 123)
    },
    -- DiffLineNumNoChangeBackground
    [80] = {
        [0] = Color3.fromRGB(27, 32, 35)
    },
    -- DiffLineNumAdditionBackground
    [81] = {
        [0] = Color3.fromRGB(55, 77, 49)
    },
    -- DiffLineNumDeletionBackground
    [82] = {
        [0] = Color3.fromRGB(91, 34, 27)
    },
    -- DiffFilePathBackground
    [83] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- DiffFilePathBorder
    [84] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- ChatIncomingBgColor
    [85] = {
        [0] = Color3.fromRGB(234, 234, 234)
    },
    -- ChatIncomingTextColor
    [86] = {
        [0] = Color3.fromRGB(57, 59, 61)
    },
    -- ChatOutgoingBgColor
    [87] = {
        [0] = Color3.fromRGB(66, 66, 66)
    },
    -- ChatOutgoingTextColor
    [88] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- ChatModeratedMessageColor
    [89] = {
        [0] = Color3.fromRGB(255, 68, 68)
    },
    -- Separator
    [90] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- ButtonBorder
    [91] = {
        [0] = Color3.fromRGB(53, 53, 53)
    },
    -- ButtonText
    [92] = {
        [0] = Color3.fromRGB(204, 204, 204),
        [1] = Color3.fromRGB(255, 255, 255),
        [3] = Color3.fromRGB(85, 85, 85)
    },
    -- InputFieldBorder
    [93] = {
        [0] = Color3.fromRGB(26, 26, 26),
        [1] = Color3.fromRGB(53, 181, 255),
        [3] = Color3.fromRGB(66, 66, 66),
        [4] = Color3.fromRGB(58, 58, 58)
    },
    -- CheckedFieldBackground
    [94] = {
        [0] = Color3.fromRGB(37, 37, 37),
        [3] = Color3.fromRGB(53, 53, 53)
    },
    -- CheckedFieldBorder
    [95] = {
        [0] = Color3.fromRGB(26, 26, 26),
        [4] = Color3.fromRGB(58, 58, 58),
        [3] = Color3.fromRGB(64, 64, 64)
    },
    -- CheckedFieldIndicator
    [96] = {
        [0] = Color3.fromRGB(53, 181, 255),
        [3] = Color3.fromRGB(85, 85, 85)
    },
    -- HeaderSection
    [97] = {
        [0] = Color3.fromRGB(53, 53, 53),
        [2] = Color3.fromRGB(41, 41, 41),
        [4] = Color3.fromRGB(72, 72, 72)
    },
    -- Midlight
    [98] = {
        [0] = Color3.fromRGB(34, 34, 34)
    },
    -- StatusBar
    [99] = {
        [0] = Color3.fromRGB(46, 46, 46)
    },
    -- DialogButton
    [100] = {
        [0] = Color3.fromRGB(60, 60, 60),
        [1] = Color3.fromRGB(51, 51, 51),
        [2] = Color3.fromRGB(51, 51, 51),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- DialogButtonText
    [101] = {
        [0] = Color3.fromRGB(204, 204, 204),
        [3] = Color3.fromRGB(102, 102, 102)
    },
    -- DialogButtonBorder
    [102] = {
        [0] = Color3.fromRGB(60, 60, 60)
    },
    -- DialogMainButton
    [103] = {
        [0] = Color3.fromRGB(0, 162, 255),
        [1] = Color3.fromRGB(0, 116, 189),
        [2] = Color3.fromRGB(0, 116, 189),
        [3] = Color3.fromRGB(60, 60, 60),
        [4] = Color3.fromRGB(50, 181, 255)
    },
    -- DialogMainButtonText
    [104] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [3] = Color3.fromRGB(102, 102, 102)
    },
    -- InfoBarWarningBackground
    [105] = {
        [0] = Color3.fromRGB(253, 251, 172)
    },
    -- InfoBarWarningText
    [106] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- ScriptEditorCurrentLine
    [107] = {
        [0] = Color3.fromRGB(45, 50, 65)
    },
    -- ScriptMethod
    [108] = {
        [0] = Color3.fromRGB(253, 251, 172)
    },
    -- ScriptProperty
    [109] = {
        [0] = Color3.fromRGB(97, 161, 241)
    },
    -- ScriptNil
    [110] = {
        [0] = Color3.fromRGB(255, 198, 0)
    },
    -- ScriptBool
    [111] = {
        [0] = Color3.fromRGB(255, 198, 0)
    },
    -- ScriptFunction
    [112] = {
        [0] = Color3.fromRGB(248, 109, 124)
    },
    -- ScriptLocal
    [113] = {
        [0] = Color3.fromRGB(248, 109, 124)
    },
    -- ScriptSelf
    [114] = {
        [0] = Color3.fromRGB(248, 109, 124)
    },
    -- ScriptLuauKeyword
    [115] = {
        [0] = Color3.fromRGB(248, 109, 124)
    },
    -- ScriptFunctionName
    [116] = {
        [0] = Color3.fromRGB(253, 251, 172)
    },
    -- ScriptTodo
    [117] = {
        [0] = Color3.fromRGB(102, 102, 102)
    },
    -- ScriptBracket
    [118] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- AttributeCog
    [119] = {
        [0] = Color3.fromRGB(170, 170, 170),
        [1] = Color3.fromRGB(204, 204, 204)
    },
    -- AICOOverlayText
    [128] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- AICOOverlayButtonBackground
    [129] = {
        [0] = Color3.fromRGB(60, 60, 60)
    },
    -- AICOOverlayButtonBackgroundHover
    [130] = {
        [0] = Color3.fromRGB(66, 66, 66)
    },
    -- AICOOverlayButtonBackgroundPressed
    [131] = {
        [0] = Color3.fromRGB(51, 51, 51)
    },
    -- OnboardingCover
    [132] = {
        [0] = Color3.fromRGB(60, 100, 250)
    },
    -- OnboardingHighlight
    [133] = {
        [0] = Color3.fromRGB(71, 133, 255)
    },
    -- OnboardingShadow
    [134] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- BreakpointMarker
    [136] = {
        [0] = Color3.fromRGB(255, 68, 68)
    },
    -- DiffLineNumHover
    [137] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- DiffLineNumSeparatorBackgroundHover
    [138] = {
        [0] = Color3.fromRGB(43, 177, 255)
    }
}