return {
    -- MainBackground
    [0] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- Titlebar
    [1] = {
        [0] = Color3.fromRGB(227, 227, 227)
    },
    -- Dropdown
    [2] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- Tooltip
    [3] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- Notification
    [4] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- ScrollBar
    [5] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [2] = Color3.fromRGB(219, 219, 219),
        [3] = Color3.fromRGB(231, 231, 231),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- ScrollBarBackground
    [6] = {
        [0] = Color3.fromRGB(238, 238, 238)
    },
    -- TabBar
    [7] = {
        [0] = Color3.fromRGB(242, 242, 242)
    },
    -- Tab
    [8] = {
        [0] = Color3.fromRGB(242, 242, 242),
        [1] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- FilterButtonDefault
    [9] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- FilterButtonHover
    [10] = {
        [0] = Color3.fromRGB(228, 238, 254)
    },
    -- FilterButtonChecked
    [11] = {
        [0] = Color3.fromRGB(219, 219, 219)
    },
    -- FilterButtonAccent
    [12] = {
        [0] = Color3.fromRGB(201, 201, 201)
    },
    -- FilterButtonBorder
    [13] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- FilterButtonBorderAlt
    [14] = {
        [0] = Color3.fromRGB(219, 219, 219)
    },
    -- RibbonTab
    [15] = {
        [0] = Color3.fromRGB(243, 243, 243),
        [1] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(255, 255, 255)
    },
    -- RibbonTabTopBar
    [16] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- Button
    [17] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [1] = Color3.fromRGB(228, 238, 254),
        [2] = Color3.fromRGB(219, 219, 219),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- MainButton
    [18] = {
        [0] = Color3.fromRGB(228, 238, 254),
        [2] = Color3.fromRGB(219, 219, 219)
    },
    -- RibbonButton
    [19] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [1] = Color3.fromRGB(219, 219, 219),
        [2] = Color3.fromRGB(219, 219, 219),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- ViewPortBackground
    [20] = {
        [0] = Color3.fromRGB(170, 170, 170)
    },
    -- InputFieldBackground
    [21] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(228, 238, 254),
        [3] = Color3.fromRGB(231, 231, 231)
    },
    -- Item
    [22] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [1] = Color3.fromRGB(104, 148, 217),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- TableItem
    [23] = {
        [0] = Color3.fromRGB(245, 245, 245),
        [1] = Color3.fromRGB(104, 148, 217),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- CategoryItem
    [24] = {
        [0] = Color3.fromRGB(233, 233, 233)
    },
    -- GameSettingsTableItem
    [25] = {
        [0] = Color3.fromRGB(245, 245, 245),
        [1] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- GameSettingsTooltip
    [26] = {
        [0] = Color3.fromRGB(117, 117, 117)
    },
    -- EmulatorBar
    [27] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- EmulatorDropDown
    [28] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [4] = Color3.fromRGB(66, 66, 66)
    },
    -- ColorPickerFrame
    [29] = {
        [0] = Color3.fromRGB(237, 237, 237)
    },
    -- CurrentMarker
    [30] = {
        [0] = Color3.fromRGB(0, 162, 255)
    },
    -- Border
    [31] = {
        [0] = Color3.fromRGB(182, 182, 182)
    },
    -- DropShadow
    [32] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- Shadow
    [33] = {
        [0] = Color3.fromRGB(238, 238, 238)
    },
    -- Light
    [34] = {
        [0] = Color3.fromRGB(243, 243, 243)
    },
    -- Dark
    [35] = {
        [0] = Color3.fromRGB(160, 160, 160)
    },
    -- Mid
    [36] = {
        [0] = Color3.fromRGB(238, 238, 238)
    },
    -- MainText
    [37] = {
        [0] = Color3.fromRGB(0, 0, 0),
        [1] = Color3.fromRGB(255, 255, 255),
        [3] = Color3.fromRGB(120, 120, 120)
    },
    -- SubText
    [38] = {
        [0] = Color3.fromRGB(107, 107, 107),
        [1] = Color3.fromRGB(204, 204, 204),
        [3] = Color3.fromRGB(120, 120, 120)
    },
    -- TitlebarText
    [39] = {
        [0] = Color3.fromRGB(0, 0, 0),
        [3] = Color3.fromRGB(199, 199, 199)
    },
    -- BrightText
    [40] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- DimmedText
    [41] = {
        [0] = Color3.fromRGB(136, 136, 136),
        [1] = Color3.fromRGB(204, 204, 204)
    },
    -- LinkText
    [42] = {
        [0] = Color3.fromRGB(53, 181, 255)
    },
    -- WarningText
    [43] = {
        [0] = Color3.fromRGB(255, 128, 0)
    },
    -- ErrorText
    [44] = {
        [0] = Color3.fromRGB(255, 0, 0)
    },
    -- InfoText
    [45] = {
        [0] = Color3.fromRGB(0, 0, 255)
    },
    -- SensitiveText
    [46] = {
        [0] = Color3.fromRGB(128, 0, 128)
    },
    -- ScriptSideWidget
    [47] = {
        [0] = Color3.fromRGB(192, 192, 192)
    },
    -- ScriptBackground
    [48] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- ScriptText
    [49] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- ScriptSelectionText
    [50] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- ScriptSelectionBackground
    [51] = {
        [0] = Color3.fromRGB(110, 161, 241)
    },
    -- ScriptFindSelectionBackground
    [52] = {
        [0] = Color3.fromRGB(255, 226, 167)
    },
    -- ScriptMatchingWordSelectionBackground
    [53] = {
        [0] = Color3.fromRGB(226, 230, 214)
    },
    -- ScriptOperator
    [54] = {
        [0] = Color3.fromRGB(127, 127, 0)
    },
    -- ScriptNumber
    [55] = {
        [0] = Color3.fromRGB(0, 127, 127)
    },
    -- ScriptString
    [56] = {
        [0] = Color3.fromRGB(127, 0, 127)
    },
    -- ScriptComment
    [57] = {
        [0] = Color3.fromRGB(0, 127, 9)
    },
    -- ScriptKeyword
    [58] = {
        [0] = Color3.fromRGB(0, 0, 127)
    },
    -- ScriptBuiltInFunction
    [59] = {
        [0] = Color3.fromRGB(127, 0, 0)
    },
    -- ScriptWarning
    [60] = {
        [0] = Color3.fromRGB(0, 0, 255)
    },
    -- ScriptError
    [61] = {
        [0] = Color3.fromRGB(255, 0, 0)
    },
    -- ScriptInformation
    [62] = {
        [0] = Color3.fromRGB(189, 189, 189)
    },
    -- ScriptHint
    [63] = {
        [0] = Color3.fromRGB(0, 139, 219)
    },
    -- ScriptWhitespace
    [64] = {
        [0] = Color3.fromRGB(184, 184, 184)
    },
    -- ScriptRuler
    [65] = {
        [0] = Color3.fromRGB(166, 166, 166)
    },
    -- DocViewCodeBackground
    [66] = {
        [0] = Color3.fromRGB(212, 212, 212)
    },
    -- DebuggerCurrentLine
    [67] = {
        [0] = Color3.fromRGB(255, 255, 204)
    },
    -- DebuggerErrorLine
    [68] = {
        [0] = Color3.fromRGB(255, 204, 204)
    },
    -- DiffFilePathText
    [69] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- DiffTextHunkInfo
    [70] = {
        [0] = Color3.fromRGB(117, 117, 117)
    },
    -- DiffTextNoChange
    [71] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- DiffTextAddition
    [72] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- DiffTextDeletion
    [73] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- DiffTextSeparatorBackground
    [74] = {
        [0] = Color3.fromRGB(236, 243, 255)
    },
    -- DiffTextNoChangeBackground
    [75] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- DiffTextAdditionBackground
    [76] = {
        [0] = Color3.fromRGB(225, 247, 232)
    },
    -- DiffTextDeletionBackground
    [77] = {
        [0] = Color3.fromRGB(255, 219, 219)
    },
    -- DiffLineNum
    [78] = {
        [0] = Color3.fromRGB(117, 117, 117)
    },
    -- DiffLineNumSeparatorBackground
    [79] = {
        [0] = Color3.fromRGB(216, 230, 255)
    },
    -- DiffLineNumNoChangeBackground
    [80] = {
        [0] = Color3.fromRGB(250, 250, 250)
    },
    -- DiffLineNumAdditionBackground
    [81] = {
        [0] = Color3.fromRGB(206, 241, 217)
    },
    -- DiffLineNumDeletionBackground
    [82] = {
        [0] = Color3.fromRGB(255, 202, 202)
    },
    -- DiffFilePathBackground
    [83] = {
        [0] = Color3.fromRGB(250, 250, 250)
    },
    -- DiffFilePathBorder
    [84] = {
        [0] = Color3.fromRGB(235, 235, 235)
    },
    -- ChatIncomingBgColor
    [85] = {
        [0] = Color3.fromRGB(245, 245, 245)
    },
    -- ChatIncomingTextColor
    [86] = {
        [0] = Color3.fromRGB(25, 25, 25)
    },
    -- ChatOutgoingBgColor
    [87] = {
        [0] = Color3.fromRGB(184, 184, 184)
    },
    -- ChatOutgoingTextColor
    [88] = {
        [0] = Color3.fromRGB(25, 25, 25)
    },
    -- ChatModeratedMessageColor
    [89] = {
        [0] = Color3.fromRGB(223, 0, 22)
    },
    -- Separator
    [90] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- ButtonBorder
    [91] = {
        [0] = Color3.fromRGB(182, 182, 182),
        [3] = Color3.fromRGB(204, 204, 204)
    },
    -- ButtonText
    [92] = {
        [0] = Color3.fromRGB(0, 0, 0),
        [3] = Color3.fromRGB(120, 120, 120)
    },
    -- InputFieldBorder
    [93] = {
        [0] = Color3.fromRGB(200, 200, 200),
        [1] = Color3.fromRGB(102, 146, 220),
        [3] = Color3.fromRGB(182, 182, 182),
        [4] = Color3.fromRGB(168, 168, 168)
    },
    -- CheckedFieldBackground
    [94] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [1] = Color3.fromRGB(0, 162, 255),
        [2] = Color3.fromRGB(219, 219, 219),
        [3] = Color3.fromRGB(200, 200, 200),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- CheckedFieldBorder
    [95] = {
        [0] = Color3.fromRGB(182, 182, 182),
        [4] = Color3.fromRGB(168, 168, 168)
    },
    -- CheckedFieldIndicator
    [96] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [3] = Color3.fromRGB(136, 136, 136)
    },
    -- HeaderSection
    [97] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [2] = Color3.fromRGB(219, 219, 219),
        [3] = Color3.fromRGB(182, 182, 182),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- Midlight
    [98] = {
        [0] = Color3.fromRGB(227, 227, 227)
    },
    -- StatusBar
    [99] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- DialogButton
    [100] = {
        [0] = Color3.fromRGB(255, 255, 255),
        [1] = Color3.fromRGB(219, 219, 219),
        [2] = Color3.fromRGB(219, 219, 219),
        [4] = Color3.fromRGB(228, 238, 254)
    },
    -- DialogButtonText
    [101] = {
        [0] = Color3.fromRGB(0, 0, 0),
        [3] = Color3.fromRGB(184, 184, 184)
    },
    -- DialogButtonBorder
    [102] = {
        [0] = Color3.fromRGB(204, 204, 204)
    },
    -- DialogMainButton
    [103] = {
        [0] = Color3.fromRGB(0, 162, 255),
        [1] = Color3.fromRGB(0, 116, 189),
        [2] = Color3.fromRGB(0, 116, 189),
        [3] = Color3.fromRGB(153, 218, 255),
        [4] = Color3.fromRGB(50, 181, 255)
    },
    -- DialogMainButtonText
    [104] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- InfoBarWarningBackground
    [105] = {
        [0] = Color3.fromRGB(253, 251, 172)
    },
    -- InfoBarWarningText
    [106] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- ScriptEditorCurrentLine
    [107] = {
        [0] = Color3.fromRGB(239, 239, 239)
    },
    -- ScriptMethod
    [108] = {
        [0] = Color3.fromRGB(0, 116, 189)
    },
    -- ScriptProperty
    [109] = {
        [0] = Color3.fromRGB(72, 92, 142)
    },
    -- ScriptNil
    [110] = {
        [0] = Color3.fromRGB(0, 127, 127)
    },
    -- ScriptBool
    [111] = {
        [0] = Color3.fromRGB(0, 127, 127)
    },
    -- ScriptFunction
    [112] = {
        [0] = Color3.fromRGB(0, 0, 127)
    },
    -- ScriptLocal
    [113] = {
        [0] = Color3.fromRGB(0, 0, 127)
    },
    -- ScriptSelf
    [114] = {
        [0] = Color3.fromRGB(0, 0, 127)
    },
    -- ScriptLuauKeyword
    [115] = {
        [0] = Color3.fromRGB(0, 0, 127)
    },
    -- ScriptFunctionName
    [116] = {
        [0] = Color3.fromRGB(0, 116, 189)
    },
    -- ScriptTodo
    [117] = {
        [0] = Color3.fromRGB(0, 127, 9)
    },
    -- ScriptBracket
    [118] = {
        [0] = Color3.fromRGB(127, 127, 0)
    },
    -- AttributeCog
    [119] = {
        [0] = Color3.fromRGB(136, 136, 136),
        [1] = Color3.fromRGB(255, 255, 255)
    },
    -- AICOOverlayText
    [128] = {
        [0] = Color3.fromRGB(86, 86, 86)
    },
    -- AICOOverlayButtonBackground
    [129] = {
        [0] = Color3.fromRGB(237, 237, 237)
    },
    -- AICOOverlayButtonBackgroundHover
    [130] = {
        [0] = Color3.fromRGB(225, 225, 225)
    },
    -- AICOOverlayButtonBackgroundPressed
    [131] = {
        [0] = Color3.fromRGB(203, 203, 203)
    },
    -- OnboardingCover
    [132] = {
        [0] = Color3.fromRGB(60, 100, 250)
    },
    -- OnboardingHighlight
    [133] = {
        [0] = Color3.fromRGB(71, 133, 255)
    },
    -- OnboardingShadow
    [134] = {
        [0] = Color3.fromRGB(0, 0, 0)
    },
    -- BreakpointMarker
    [136] = {
        [0] = Color3.fromRGB(255, 68, 68)
    },
    -- DiffLineNumHover
    [137] = {
        [0] = Color3.fromRGB(255, 255, 255)
    },
    -- DiffLineNumSeparatorBackgroundHover
    [138] = {
        [0] = Color3.fromRGB(43, 177, 255)
    }
}